apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "bidrag-pdfgen"
  namespace: "bidrag"
  labels:
    team: bidrag
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "1001"
    nais.io/run-as-group: "1001"
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  image: {{ image }}
  port: 8080
  accessPolicy:
    inbound:
      rules:
      {{#each azure_access_inbound}}
         - application: {{this.application}}
      {{/each}}
    outbound:
      rules:
      {{#each outbound-access-apps}}
         - application: {{this}}
      {{/each}}
  liveness:
    path: /health
    initialDelay: 10
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /health
    initialDelay: 10
    timeout: 1
  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 500Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  command:
   - gotenberg
   - --pdfengines-engines=libreoffice-pdfengine
   - --api-port=8080