ingresses:
  - https://bidrag-dokument-produksjon.intern.dev.nav.no
azure_access_inbound:
  - application: bidrag-ui-feature
  - application: bidrag-ui
  - application: bidrag-behandling
  - application: bidrag-behandling-feature
outbound-access-apps:
  - bidrag-dokumentmal
  - bidrag-pdfgen
env:
  PDFGEN_VERSION: V2