ingresses:
  - https://bidrag-dokument-produksjon.intern.dev.nav.no
azure_access_inbound:
  - application: bidrag-behandling-q1
    namespace: bidrag
    cluster: dev-gcp
  - application: bidrag-behandling-q2
    namespace: bidrag
    cluster: dev-gcp
  - application: bidrag-behandling-q2
    namespace: bidrag
    cluster: dev-gcp
  - application: bidrag-ui
    namespace: bidrag
    cluster: dev-fss
  - application: bidrag-ui-feature
    namespace: bidrag
    cluster: dev-fss
outbound-access-apps:
  - bidrag-dokumentmal
  - bidrag-pdfgen
env:
  PDFGEN_VERSION: V2