ingresses:
  - https://bidrag-dokument-produksjon.intern.nav.no
azure_access_inbound:
  - application: bidrag-ui
  - application: bidrag-behandling
  - application: bidrag-bidragskalkulator-api
outbound-access-apps:
  - bidrag-dokumentmal
  - bidrag-pdfgen
env:
  PDFGEN_VERSION: V2
