ingresses:
  - https://bidrag-dokument-produksjon.intern.nav.no
azure_access_inbound:
  - application: bidrag-dokumentmal
    namespace: bidrag
    cluster: prod-gcp
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss
outbound-access-apps:
  - bidrag-dokumentmal
  - bidrag-pdfgen
env:
  PDFGEN_VERSION: V2