name: Deploy feature
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!dependabot/**'

jobs:
  build-deploy:
    name: "Build and deploy to feature"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@github_server_2
    secrets: inherit
    with:
      maven_options: -B -q -fae -Pit