name: Deploy to dev
on:
  workflow_dispatch:
  pull_request:
    types: [ ready_for_review, opened, synchronize ]

jobs:
  build-deploy:
    name: "Build and deploy to main"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@github_server_2
    secrets: inherit
    with:
      nais_variabler_filnavn: dev.yaml
      maven_options: -B -q -fae -Pit